services:
  clio-minimal:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: clio-minimal-container
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11312
      - ROS_HOSTNAME=localhost
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./datasets:/datasets:ro
      - ./clio_workspace:/catkin_ws
    ports:
      - "11312:11311"  # ROS master (using different port to avoid conflicts)
    working_dir: /catkin_ws
    stdin_open: true
    tty: true
    restart: unless-stopped
